# This is a basic workflow to help you get started with Actions

name: Build and install on remote server.

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run build script
        run: ./build.sh
      
      - name: Verify build
        id: verify_build
        uses: andstor/file-existence-action@v1
        with:
          allow_failure: true
          files: "dist/bin/openlitespeed"
            
      - name: Copy to remote server
        if: steps.verify_build.outputs.files_exists == 'true'
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist/bin/openlitespeed
          remote: gh-action/openlitespeed
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          rmRemote: true
          dotfiles: true
          
      - name: Install
        if: steps.verify_build.outputs.files_exists == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            rm -rf /usr/local/lsws/bin/openlitespeed
            cp ~/gh-action/openlitespeed /usr/local/lsws/bin/openlitespeed
            chmod +x /usr/local/lsws/bin/openlitespeed
            systemctl restart lsws
